"""
Planning Agent
--------------
Reads a Jira ticket and produces a technical implementation plan.
Decomposes the ticket into subtasks and flags risks or missing information.

Trigger: Ticket status → "Ready for Dev" (Jira webhook).
Output:  Implementation plan written to Jira ticket comment + TicketState.
"""

import logging
from langchain_core.messages import SystemMessage, HumanMessage

from shared.models.llm_factory import get_llm, LLMProfile
from shared.tools.jira_tool import JiraTool
from shared.tools.slack_tool import SlackTool
from shared.state.ticket_state import TicketState, TicketStatus

logger = logging.getLogger(__name__)

SYSTEM_PROMPT = """\
You are the Technical Planning Agent.

Given a Jira ticket, produce a concise technical implementation plan that a senior engineer
would be happy to hand off to a junior developer or a code-generation agent.

Include:
1. Approach — which files/modules to change and why
2. API changes — new endpoints, modified request/response schemas
3. Data model changes — new tables, fields, migrations needed
4. Dependencies — new libraries or services required
5. Edge cases — things the implementation must handle correctly
6. Risks — unknowns, potential blockers, things to clarify before starting

Keep it under 500 words. Use bullet points. Be specific about file paths and function names
where possible based on common patterns.

Output plain markdown — no JSON, no extra wrapping.
"""


class PlanningAgent:
    def __init__(self, notify_channel: str = "#dev-agents"):
        self._llm     = get_llm(LLMProfile.SONNET)
        self._jira    = JiraTool()
        self._slack   = SlackTool()
        self._channel = notify_channel

    def run(self, state: TicketState) -> TicketState:
        logger.info("PlanningAgent: planning %s", state.ticket_id)

        plan = self._generate_plan(state)
        state.implementation_plan = plan

        # Post plan to Jira as a comment
        self._jira.add_comment(
            state.ticket_id,
            f"**AI Implementation Plan**\n\n{plan}\n\n---\n*Generated by planning-agent. Tech lead approval required before coding starts.*",
        )

        # Human gate — tech lead approval via Slack
        state.set_gate("tech_lead_review", timeout_hours=24)
        self._slack.request_approval(
            channel=self._channel,
            gate_name="Tech Lead: Implementation Plan",
            ticket_id=state.ticket_id,
            summary=plan[:400] + "...",
            details_url=state.ticket_url,
            callback_id=f"gate_tech_lead_{state.ticket_id}",
        )

        state.status = TicketStatus.PLANNING
        state.record_step(agent="planning-agent", success=True, summary="Implementation plan posted to Jira")
        return state

    def _generate_plan(self, state: TicketState) -> str:
        prompt = f"""
Ticket: {state.ticket_id} — {state.title}

Description:
{state.description}

Acceptance Criteria:
{chr(10).join(f'- {ac}' for ac in state.acceptance_criteria)}
"""
        messages = [SystemMessage(content=SYSTEM_PROMPT), HumanMessage(content=prompt)]
        response = self._llm.invoke(messages)
        return response.content.strip()
